### ISSUE TITLE
GNU make fails on Windows 10

### ISSUE THREAD

**Issue by alex-lechner** [kuzzleio/sdk-python3#3]
There's an issue in any of the Makefiles (either `sdk-python3`, `sdk-cpp` or `sdk-c`) for Windows. Unfortunately, I don't know where the exact problem is because I don't know GNU syntax.

BTW: The execution order in the README is wrong. It should be
```sh
git clone --recursive git@github.com:kuzzleio/sdk-python3.git
cd sdk-python3
git submodule update --init --recursive
make
```

## Expected Behavior

The successful execution of `make`.

## Current Behavior

When I execute `make` the following error appears:
```sh
E:\projects\sdk-python3>make
rm -rf .\\sdk-cpp\\sdk-c\\build\\*.so*
process_begin: CreateProcess(NULL, rm -rf .\sdk-cpp\sdk-c\build\*.so*, ...) failed.
make (e=2): Das System kann die angegebene Datei nicht finden.
Makefile:63: recipe for target 'remove_so' failed
make: *** [remove_so] Error 2
```

When I execute `make -n` the following error appears:
```sh
E:\projects\sdk-python3>make -n
rm -rf .\\sdk-cpp\\sdk-c\\build\\*.so*
if not exist E:\projects\sdk-python3\\build mkdir E:\projects\sdk-python3\\build
cd sdk-cpp/sdk-c && make
make[1]: Entering directory 'E:/projects/sdk-python3/sdk-cpp/sdk-c'
if not exist E:\projects\sdk-python3\sdk-cpp\sdk-c\build mkdir E:\projects\sdk-python3\sdk-cpp\sdk-c\build
cd go\\src\\github.com\\kuzzleio\\sdk-go && go get .\\...
C:\Go\bin\go build -o E:/projects/sdk-python3/sdk-cpp/sdk-c/build\\kuzzlesdk.lib -buildmode=c-archive .\\cgo\\kuzzle\\
C:\Go\bin\go build -o E:/projects/sdk-python3/sdk-cpp/sdk-c/build\\kuzzlesdk.dll -buildmode=c-shared .\\cgo\\kuzzle\\
rename E:\projects\sdk-python3\sdk-cpp\sdk-c\build\\kuzzlesdk.h kuzzle.h
cd E:/projects/sdk-python3/sdk-cpp/sdk-c/build && mv E:/projects/sdk-python3/sdk-cpp/sdk-c/build\\kuzzlesdk.lib E:/projects/sdk-python3/sdk-cpp/sdk-c/build\\kuzzlesdk.lib.1.0.0 && mv E:/projects/sdk-python3/sdk-cpp/sdk-c/build\\kuzzlesdk.dll E:/projects/sdk-python3/sdk-cpp/sdk-c/build\\kuzzlesdk.dll.1.0.0
cd E:/projects/sdk-python3/sdk-cpp/sdk-c/build && ln -sr kuzzlesdk.lib.1.0.0 kuzzlesdk.lib
cd E:/projects/sdk-python3/sdk-cpp/sdk-c/build && ln -sr kuzzlesdk.dll.1.0.0 kuzzlesdk.dll
make[1]: Leaving directory 'E:/projects/sdk-python3/sdk-cpp/sdk-c'
swig -Wall -c++ -python -py3 -outdir E:/projects/sdk-python3//build -o kcore_wrap.cxx -I.\\sdk-cpp\\include -I.\\sdk-cpp\\sdk-c\\include\\ -I.\\sdk-cpp\\src -I.\\sdk-cpp\\sdk-c\\build\\ `pkg-config --cflags python3` swig/core.i
make: *** No rule to make target 'kcore_wrap.cxx', needed by 'kcore_wrap.o'.  Stop.
```

## Possible Solution

/

## Steps to Reproduce

1. Windows 10 as OS
2. Download and install MinGW, go to `C:\MinGW\bin` and rename `mingw32-make.exe` to `make.exe`
3. set `C:\MinGW\bin` in the System's `Path` environment variable
4. Clone this repository in the folder of your choice, update the repository's submodules like described in the README and execute `make` in the CMD-shell in the folder

## Context (Environment)

/

**Comment by Aschen** [comment]
Hi @alex-lechner !

I'm glad to see that our futur python SDK start to interest people :-) 

Unfortunately for you, this is still a work in progress. We have to write the SWIG template to correctly generate python code based on the shared C++ library. 

For now it's better to use Kuzzle with raw python. @etrousset  from our team has developed a small unofficial python sdk: https://github.com/etrousset/py-kuzzle-iot.

If you really need the official Python SDK right now, you can ask for professional support on our website: https://info.kuzzle.io/contact-us

**Comment by alex-lechner** [comment]
Hey @Aschen ,
Thanks for the fast reply! I see, I will have to find another way and wait for the next release I guess.
It's not urgent, just wanted to play around and test it 😃 
Thank you for the links and I'm excited when the SDK is ready to use!
All the best, Alex

**Comment by Aschen** [comment]
We will let you know when the SDK is ready to use !
Hope you will enjoy working with Kuzzle :)
